apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: 629434592/customer
          env:
            - name: MONGO_URI
              value: 'mongodb://customer-mongo-serv:27017/customer'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: customer-serv
spec:
  selector:
    app: customer
  ports:
    - name: customer
      protocol: TCP
      port: 3000
      targetPort: 3000
